<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log inLog in dengan QR</name>
   <tag></tag>
   <elementGuidId>f5894b44-8ab2-4ce3-99d1-e5824d1844fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.KhSVKK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div/div/div/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Log inLog in dengan QR&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9667e48a-22cc-4737-9ee1-2ddf1c8c5cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>KhSVKK</value>
      <webElementGuid>5d11a25a-dee7-4dd0-9a28-b4c3005029c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log inLog in dengan QR</value>
      <webElementGuid>bfb080d3-ae44-4372-ab8f-50ecb3b9e486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;t5pFIU&quot;]/div[@class=&quot;kr8eST&quot;]/div[@class=&quot;r0dQ_c&quot;]/div[1]/div[@class=&quot;UCVQlJ KeDAsM&quot;]/div[@class=&quot;WMXxSA&quot;]/div[2]/div[@class=&quot;VAy83y mylGx2&quot;]/div[@class=&quot;_92W8Vw&quot;]/div[@class=&quot;KhSVKK&quot;]</value>
      <webElementGuid>0dd7ac7e-8933-4a94-9d94-0b5bc80dcf05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>6e5fee74-c305-48b5-9d66-4ed0c2790baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Butuh bantuan?'])[1]/following::div[8]</value>
      <webElementGuid>79589360-f5f3-4999-ba36-167f52fb68c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::div[8]</value>
      <webElementGuid>292de512-d44b-4c51-88fb-0a0f54ab943b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div/div</value>
      <webElementGuid>deb9197f-46d0-4e20-89b6-b6b047898ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Log inLog in dengan QR' or . = 'Log inLog in dengan QR')]</value>
      <webElementGuid>357603b6-23d2-48a3-a8d6-660c126df1dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
