<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log in dengan QR_authentication-input-e_30da96</name>
   <tag></tag>
   <elementGuidId>4b2d3579-6e4c-4771-970f-aabd552f7380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#authentication-input-error_51b719be-2d3d-40ee-ab18-8a23e220d72c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='authentication-input-error_51b719be-2d3d-40ee-ab18-8a23e220d72c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#authentication-input-error_51b719be-2d3d-40ee-ab18-8a23e220d72c</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f2081624-6b08-4bf1-b192-beb14ada2990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>authentication-input-error_51b719be-2d3d-40ee-ab18-8a23e220d72c</value>
      <webElementGuid>79be0338-f311-40e9-bdca-60867f203d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NLNOLc</value>
      <webElementGuid>d47507b5-9861-4f15-8a33-14d18558e479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>c57590f6-3b07-4fbe-b9cc-71e3a63fbd62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authentication-input-error_51b719be-2d3d-40ee-ab18-8a23e220d72c&quot;)</value>
      <webElementGuid>d9afcb55-f75b-4328-92a9-55199775bb36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='authentication-input-error_51b719be-2d3d-40ee-ab18-8a23e220d72c']</value>
      <webElementGuid>3761e429-ec47-4b28-9358-13116e48b437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/form/div/div[2]</value>
      <webElementGuid>6dc7fdc6-72fd-4891-b304-d8259dffc961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]</value>
      <webElementGuid>3d25c9fc-1459-4040-b9d4-10a83a60f4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'authentication-input-error_51b719be-2d3d-40ee-ab18-8a23e220d72c']</value>
      <webElementGuid>96e1a0c9-9376-461b-be16-1d73ce97fd87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
