<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log in dengan QR_authentication-input-e_6b681a</name>
   <tag></tag>
   <elementGuidId>d8a848ec-7e10-45a0-be87-86cea19e2820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#authentication-input-error_610c8f4d-d901-44c5-8be4-e396e92976d0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='authentication-input-error_610c8f4d-d901-44c5-8be4-e396e92976d0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#authentication-input-error_610c8f4d-d901-44c5-8be4-e396e92976d0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>80fb6fd7-f2a6-4aba-b611-ca6a26eed9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>authentication-input-error_610c8f4d-d901-44c5-8be4-e396e92976d0</value>
      <webElementGuid>560153f2-9566-4860-9068-5fd2b1d7ba32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NLNOLc</value>
      <webElementGuid>1dbf1719-fdff-48cd-898f-588604d95092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>7c46a0c4-6be7-4739-863c-821e29c0cf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authentication-input-error_610c8f4d-d901-44c5-8be4-e396e92976d0&quot;)</value>
      <webElementGuid>3c54749b-6cf2-49e2-990a-894259fc9beb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='authentication-input-error_610c8f4d-d901-44c5-8be4-e396e92976d0']</value>
      <webElementGuid>e7766ecb-112f-40a6-b32e-20184c361c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/form/div[2]/div[2]</value>
      <webElementGuid>7f892cb9-b0f6-4065-8cf7-89d3c8cb129d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div[2]</value>
      <webElementGuid>8288aa9a-1818-405a-a5e2-25197eba619e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'authentication-input-error_610c8f4d-d901-44c5-8be4-e396e92976d0']</value>
      <webElementGuid>714a4f87-6f54-49d4-8b3f-5e934620889a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
